import express from "express";
import pool from "../db.js";
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";

const router = express.Router();


router.get("/", async(req,res)=>{

try{

const employees = await pool.query(
"SELECT COUNT(*) FROM employees"
);


const projects = await pool.query(
"SELECT COUNT(*) FROM projects"
);


const inventory = await pool.query(
`
SELECT 
SUM(quantity * unit_price) AS value
FROM inventory
`
);


const invoices = await pool.query(
`
SELECT 
SUM(amount) AS value
FROM invoices
`
);


const ledger = await pool.query(
`
SELECT 
SUM(
CASE 
WHEN type='Credit' THEN amount
ELSE -amount
END
) AS balance
FROM ledger_entries
`
);


res.json({

employees:employees.rows[0].count,
projects:projects.rows[0].count,
inventoryValue:
inventory.rows[0].value || 0,
invoiceValue:
invoices.rows[0].value || 0,
ledgerBalance:
ledger.rows[0].balance || 0
});
}
catch(err){
console.log(err);
res.status(500).json({
message:"Report Error"
});
}
});

router.get("/pdf", async (req, res) => {
  try {
    const employees = await pool.query("SELECT COUNT(*) FROM employees");
    const projects = await pool.query("SELECT COUNT(*) FROM projects");
    const inventory = await pool.query(
      "SELECT SUM(quantity * unit_price) AS value FROM inventory"
    );
    const invoices = await pool.query(
      "SELECT SUM(amount) AS value FROM invoices"
    );
    const ledger = await pool.query(`
      SELECT SUM(
        CASE
          WHEN type='Credit' THEN amount
          ELSE -amount
        END
      ) AS balance
      FROM ledger_entries
    `);

    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=Analytics_Report.pdf"
    );

    doc.pipe(res);

    // ================= HEADER =================

    doc.rect(0, 0, 612, 90).fill("#1E40AF");

    doc
      .fillColor("white")
      .font("Helvetica-Bold")
      .fontSize(24)
      .text("AMDOX ERP", 40, 28);

    doc
      .font("Helvetica")
      .fontSize(12)
      .text("Enterprise Resource Planning System", 40, 58);

    // ================= TITLE =================

    doc.fillColor("black");

    doc
      .font("Helvetica-Bold")
      .fontSize(20)
      .text("Analytics Report", 40, 120);

    doc
      .font("Helvetica")
      .fontSize(11)
      .text(
        `Generated On : ${new Date().toLocaleString()}`,
        40,
        150
      );

    // ================= TABLE =================

    const rows = [
      [
        "Employees",
        employees.rows[0].count,
      ],
      [
        "Projects",
        projects.rows[0].count,
      ],
      [
        "Inventory Value",
        `₹${Number(
          inventory.rows[0].value || 0
        ).toLocaleString("en-IN")}`,
      ],
      [
        "Invoice Value",
        `₹${Number(
          invoices.rows[0].value || 0
        ).toLocaleString("en-IN")}`,
      ],
      [
        "Ledger Balance",
        `₹${Number(
          ledger.rows[0].balance || 0
        ).toLocaleString("en-IN")}`,
      ],
    ];

    let y = 200;

    // Header Background
    doc.rect(40, y, 520, 30).fill("#2563EB");

    doc
      .fillColor("white")
      .font("Helvetica-Bold")
      .fontSize(12);

    doc.text("Metric", 60, y + 8, {
      width: 250,
    });

    doc.text("Value", 340, y + 8, {
      width: 180,
      align: "right",
    });

    y += 30;

    rows.forEach((row, index) => {

      if (index % 2 === 0) {
        doc
          .fillColor("#F8FAFC")
          .rect(40, y, 520, 30)
          .fill();
      }

      doc
        .strokeColor("#D1D5DB")
        .rect(40, y, 520, 30)
        .stroke();

      doc.fillColor("black");

      doc
        .font("Helvetica")
        .fontSize(11);

      doc.text(row[0], 60, y + 8, {
        width: 250,
      });

      doc.text(String(row[1]), 340, y + 8, {
        width: 180,
        align: "right",
      });

      y += 30;
    });

    // ================= FOOTER =================

    doc
      .fontSize(10)
      .fillColor("gray")
      .text(
        "Generated by AMDOX ERP",
        40,
        760
      );

    doc.end();

  } catch (err) {
    console.log(err);
    res.status(500).json({
      message: "PDF Export Failed",
    });
  }
});

router.get("/excel", async (req, res) => {

  try {

    const workbook = new ExcelJS.Workbook();

    workbook.creator = "AMDOX ERP";
    workbook.created = new Date();


    const sheet = workbook.addWorksheet("Analytics Report");


    const employees = await pool.query(
      "SELECT COUNT(*) FROM employees"
    );

    const projects = await pool.query(
      "SELECT COUNT(*) FROM projects"
    );

    const inventory = await pool.query(
      "SELECT SUM(quantity * unit_price) AS value FROM inventory"
    );

    const invoices = await pool.query(
      "SELECT SUM(amount) AS value FROM invoices"
    );

    const ledger = await pool.query(`
      SELECT SUM(
        CASE
          WHEN type='Credit' THEN amount
          ELSE -amount
        END
      ) AS balance
      FROM ledger_entries
    `);



    // ================= TITLE =================

    sheet.mergeCells("A1:B1");

    const title = sheet.getCell("A1");

    title.value = "AMDOX ERP - Analytics Report";

    title.font = {
      bold:true,
      size:18,
      color:"FFFFFF"
    };

    title.alignment = {
      horizontal:"center"
    };

    title.fill = {
      type:"pattern",
      pattern:"solid",
      fgColor:{
        rgb:"1E40AF"
      }
    };


    sheet.mergeCells("A2:B2");

    sheet.getCell("A2").value =
      `Generated On : ${new Date().toLocaleString()}`;


    sheet.getCell("A2").alignment={
      horizontal:"center"
    };



    // ================= TABLE HEADER =================


    sheet.addRow([]);

    const header = sheet.addRow([
      "Metric",
      "Value"
    ]);


    header.eachCell((cell)=>{

      cell.font={
        bold:true,
        color:"FFFFFF"
      };

      cell.fill={
        type:"pattern",
        pattern:"solid",
        fgColor:{
          rgb:"2563EB"
        }
      };

      cell.alignment={
        horizontal:"center"
      };

    });



    // ================= DATA =================


    const data = [

      [
        "Employees",
        Number(employees.rows[0].count)
      ],

      [
        "Projects",
        Number(projects.rows[0].count)
      ],

      [
        "Inventory Value",
        Number(inventory.rows[0].value || 0)
      ],

      [
        "Invoice Value",
        Number(invoices.rows[0].value || 0)
      ],

      [
        "Ledger Balance",
        Number(ledger.rows[0].balance || 0)
      ]

    ];



    data.forEach((row,index)=>{

      const excelRow = sheet.addRow(row);


      if(index % 2 === 0){

        excelRow.eachCell((cell)=>{

          cell.fill={
            type:"pattern",
            pattern:"solid",
            fgColor:{
              rgb:"F1F5F9"
            }
          };

        });

      }

    });



    // ================= FORMATTING =================


    sheet.columnWidths = {
      A:25,
      B:20
    };


    sheet.getColumn(1).width = 30;
    sheet.getColumn(2).width = 20;



    // Currency formatting

    for(let i=6;i<=10;i++){

      sheet.getCell(`B${i}`).numFmt =
      '₹#,##0';

    }



    // Borders

    sheet.eachRow((row)=>{

      row.eachCell((cell)=>{

        cell.border={

          top:{
            style:"thin",
          },

          left:{
            style:"thin",
          },

          bottom:{
            style:"thin",
          },

          right:{
            style:"thin",
          }

        };

      });

    });



    // Freeze header

    sheet.views = [
      {
        state:"frozen",
        ySplit:4
      }
    ];



    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    );


    res.setHeader(
      "Content-Disposition",
      "attachment; filename=AMDOX_Analytics_Report.xlsx"
    );


    await workbook.xlsx.write(res);

    res.end();


  } catch(err){

    console.log(err);

    res.status(500).json({
      message:"Excel Export Failed"
    });

  }

});

router.get("/recent-activity", async (req, res) => {

  try {

    const result = await pool.query(`
      SELECT
        action,
        module,
        username,
        created_at
      FROM audit_logs
      ORDER BY created_at DESC
      LIMIT 10
    `);

    res.json(result.rows);

  } catch (err) {

    console.log(err);

    res.status(500).json({
      message: "Failed to load recent activity"
    });

  }

});

export default router;